function findAISignatures(text: string, treshold: number = 1): number {
    // find ai signatures in the text that suggest it was generated by an ai language model
    // for example em dashes
    // emojis in the text
    // certain phrases like "as an ai language model"
    // numeration styles like "1.", "2.", "3."
    let score = 0;
    const emDashCount = (text.match(/—/g) || []).length;
    score += emDashCount * 0.3;

    // find emojis
    const emojiCount = (text.match(/[\u{1F600}-\u{1F64F}]/gu) || []).length;
    score += emojiCount * 0.5;

    // find phrases
    const aiPhrases = [
        'as an ai language model',
        'i am an ai',
        'i am an artificial intelligence',
        'as an artificial intelligence',
    ];
    for (const phrase of aiPhrases) {
        const phraseCount = (text.toLowerCase().match(new RegExp(phrase, 'g')) || []).length;
        score += phraseCount * 1;
    }

    // find numeration styles
    const numerationCount = (text.match(/\b\d+\./g) || []).length;
    score += numerationCount * 0.05;

    if (score > treshold) {
        return 1
    }
    return 0;
}